# Basic colors
foreground              #e4e1e9
background              #131318
selection_foreground    #e1e0f9
selection_background    #444559

# Cursor colors
cursor                  #bec2ff
cursor_text_color       #272b60

# URL underline color when hovering with mouse
url_color               #e8b9d5

# Kitty window border colors
active_border_color     #bec2ff
inactive_border_color   #46464f
bell_border_color       #ffb4ab

# OS Window titlebar colors
wayland_titlebar_color  system
macos_titlebar_color    system

# Tab bar colors
active_tab_foreground   #e0e0ff
active_tab_background   #3d4278
inactive_tab_foreground #c7c5d0
inactive_tab_background #1f1f25
tab_bar_background      #131318

# Colors for marks
mark1_foreground #272b60
mark1_background #bec2ff
mark2_foreground #2e2f42
mark2_background #c5c4dd
mark3_foreground #46263b
mark3_background #e8b9d5

# The 16 terminal colors
# black
color0 #46464f
color8 #91909a

# red
color1 #ffb4ab
color9 #93000a

# green
color2  #bec2ff
color10 #e0e0ff

# yellow
color3  #e8b9d5
color11 #ffd8ee

# blue
color4  #c5c4dd
color12 #e1e0f9

# magenta
color5  #3d4278
color13 #555a92

# cyan
color6  #444559
color14 #5e3c53

# white
color7  #c7c5d0
color15 #e4e1e9
