#!/usr/bin/env bash

set -u

DESIGN="$HOME/.config/hypr/design.json"
OUT="$HOME/.config/hypr/config/design.conf"

[ -f "$DESIGN" ] || exit 1

BLUR_ENABLED="$(
    jq -r '.blurEnabled // true' "$DESIGN"
)"

BLUR_SIZE="$(
    jq -r '.blurSize // 8' "$DESIGN"
)"

BLUR_PASSES="$(
    jq -r '.blurPasses // 2' "$DESIGN"
)"

if [ "$BLUR_ENABLED" = "true" ]; then
    ENABLED="true"
else
    ENABLED="false"
fi

cat > "$OUT" <<EOC
# ============================================================
# AUTOGENERATED FROM ~/.config/hypr/design.json
# ============================================================

decoration {
    blur {
        enabled = $ENABLED
        size = $BLUR_SIZE
        passes = $BLUR_PASSES
        new_optimizations = true
    }
}
EOC

hyprctl reload >/dev/null 2>&1 || true
