#!/usr/bin/env bash
set -u

SETTINGS_FILE="$HOME/.config/hypr/settings.json"
CONF_DIR="$HOME/.config/hypr/config"
ENV_FILE="$HOME/.config/hypr/scripts/quickshell/calendar/.env"
WEATHER_SCRIPT="$HOME/.config/hypr/scripts/weather.sh"
ZSH_RC="$HOME/.zshrc"

mkdir -p "$CONF_DIR" "$(dirname "$SETTINGS_FILE")" "$(dirname "$ENV_FILE")"
[ -f "$SETTINGS_FILE" ] || echo '{}' > "$SETTINGS_FILE"

compile_settings() {
    echo "Regenerating Lua configuration from settings.json..."

    local old_hash new_hash
    old_hash="$(
        md5sum \
            "$CONF_DIR/generated_env.lua" \
            "$CONF_DIR/generated_monitors.lua" \
            "$CONF_DIR/generated_keybindings.lua" \
            "$CONF_DIR/generated_autostart.lua" \
            2>/dev/null | md5sum | awk '{print $1}'
    )"

    local pic_dir vid_dir
    pic_dir="$(xdg-user-dir PICTURES 2>/dev/null || printf '%s/Pictures' "$HOME")"
    vid_dir="$(xdg-user-dir VIDEOS 2>/dev/null || printf '%s/Videos' "$HOME")"

    export AVE_PIC_DIR="$pic_dir"
    export AVE_VID_DIR="$vid_dir"

    python3 - "$SETTINGS_FILE" "$CONF_DIR" <<'PY'
import json
import os
import shlex
import sys
from pathlib import Path

settings_path = Path(sys.argv[1])
conf_dir = Path(sys.argv[2])

try:
    data = json.loads(settings_path.read_text(encoding="utf-8"))
except Exception as e:
    raise SystemExit(f"settings.json parse error: {e}")

def lua_quote(value):
    # JSON double-quoted strings are valid for the strings used here in Lua.
    return json.dumps(str(value), ensure_ascii=False)

def write_atomic(path, text):
    path = Path(path)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)

home = str(Path.home())
pic_dir = os.environ.get("AVE_PIC_DIR", home + "/Pictures")
vid_dir = os.environ.get("AVE_VID_DIR", home + "/Videos")
wallpaper_dir = data.get("wallpaperDir") or (home + "/Pictures/Wallpapers")
language = data.get("language") or "us"
kb_options = data.get("kbOptions") or "grp:alt_shift_toggle"

# ---- generated_env.lua ----
env_lines = [
    "-- AUTOGENERATED FROM settings.json -- DO NOT EDIT",
    f'hl.env("NIXOS_OZONE_WL", "1")',
    f'hl.env("XDG_PICTURES_DIR", {lua_quote(pic_dir)})',
    f'hl.env("XDG_VIDEOS_DIR", {lua_quote(vid_dir)})',
    f'hl.env("WALLPAPER_DIR", {lua_quote(wallpaper_dir)})',
    f'hl.env("SCRIPT_DIR", {lua_quote(home + "/.config/hypr/scripts")})',
    f'hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")',
    "",
    '-- NVIDIA / graphics environment preserved from the old config',
    'hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")',
    'hl.env("__NV_PRIME_RENDER_OFFLOAD", "1")',
    'hl.env("__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "NVIDIA-G0")',
    'hl.env("__GL_GSYNC_ALLOWED", "0")',
    'hl.env("__GL_VRR_ALLOWED", "0")',
    'hl.env("__GL_SHADER_DISK_CACHE", "1")',
    f'hl.env("__GL_SHADER_DISK_CACHE_PATH", {lua_quote(home + "/.cache/nvidia")})',
    'hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")',
    'hl.env("LIBVA_DRIVER_NAME", "nvidia")',
    "",
    'hl.config({',
    '  input = {',
    f'    kb_layout = {lua_quote(language)},',
    f'    kb_options = {lua_quote(kb_options)},',
    '  },',
    '})',
    "",
]
write_atomic(conf_dir / "generated_env.lua", "\n".join(env_lines) + "\n")

# ---- generated_monitors.lua ----
monitors = data.get("monitors") or []
mon_lines = ["-- AUTOGENERATED FROM settings.json -- DO NOT EDIT"]
if not monitors:
    mon_lines += [
        "hl.monitor({",
        '  output = "",',
        '  mode = "preferred",',
        '  position = "auto",',
        '  scale = 1.0,',
        "})",
    ]
else:
    for m in monitors:
        name = m.get("name", "")
        rw = m.get("resW", 0)
        rh = m.get("resH", 0)
        rate = m.get("rate", 60)
        x = m.get("x", 0)
        y = m.get("y", 0)
        scale = m.get("scale", 1.0)
        transform = m.get("transform", 0)

        mon_lines += [
            "hl.monitor({",
            f"  output = {lua_quote(name)},",
            f"  mode = {lua_quote(f'{rw}x{rh}@{rate:g}')},",
            f"  position = {lua_quote(f'{x}x{y}')},",
            f"  scale = {float(scale)},",
        ]
        if transform:
            mon_lines.append(f"  transform = {int(transform)},")
        mon_lines.append("})")
        mon_lines.append("")
write_atomic(conf_dir / "generated_monitors.lua", "\n".join(mon_lines) + "\n")

# ---- generated_keybindings.lua ----
def normalize_mods(mods):
    mods = str(mods or "")
    mods = mods.replace("$mainMod", "SUPER")
    replacements = {
        "SHIFT_L": "SHIFT", "SHIFT_R": "SHIFT",
        "CTRL_L": "CTRL", "CTRL_R": "CTRL",
        "ALT_L": "ALT", "ALT_R": "ALT",
        "SUPER_L": "SUPER", "SUPER_R": "SUPER",
    }
    for a, b in replacements.items():
        mods = mods.replace(a, b)
    return " ".join(mods.split())

def typed_dispatcher(dispatcher, command):
    d = (dispatcher or "exec").strip()
    c = (command or "").strip()

    if d == "exec":
        return f"hl.dsp.exec_cmd({lua_quote(c)})"
    if d == "killactive":
        return "hl.dsp.window.close()"
    if d == "togglefloating":
        return 'hl.dsp.window.float({ action = "toggle" })'
    if d == "fullscreen":
        return 'hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" })'
    if d == "pseudo":
        return "hl.dsp.window.pseudo()"
    if d == "layoutmsg":
        return f"hl.dsp.layout({lua_quote(c)})"
    if d == "exit":
        return "hl.dsp.exit()"
    if d == "workspace":
        return f"hl.dsp.focus({{ workspace = {lua_quote(c)} }})"
    if d == "movetoworkspace":
        return f"hl.dsp.window.move({{ workspace = {lua_quote(c)} }})"
    if d == "movefocus":
        dirs = {"l": "left", "r": "right", "u": "up", "d": "down"}
        direction = dirs.get(c, c)
        return f"hl.dsp.focus({{ direction = {lua_quote(direction)} }})"
    if d == "movewindow":
        return "hl.dsp.window.drag()"
    if d == "resizewindow":
        return "hl.dsp.window.resize()"

    shell_cmd = "hyprctl dispatch " + shlex.quote(d)
    if c:
        shell_cmd += " " + shlex.quote(c)
    return f"hl.dsp.exec_cmd({lua_quote(shell_cmd)})"

kb_lines = ["-- AUTOGENERATED FROM settings.json -- DO NOT EDIT"]
for item in data.get("keybinds") or []:
    typ = str(item.get("type") or "bind").lower()
    mods = normalize_mods(item.get("mods"))
    key = str(item.get("key") or "").strip()
    dispatcher = str(item.get("dispatcher") or "exec")
    command = str(item.get("command") or "")

    if not key:
        continue

    key_expr = f"{mods} + {key}" if mods else key
    action = typed_dispatcher(dispatcher, command)

    flags = []
    suffix = typ[4:] if typ.startswith("bind") else ""
    if "e" in suffix:
        flags.append("repeating = true")
    if "l" in suffix:
        flags.append("locked = true")
    if "m" in suffix:
        flags.append("mouse = true")

    if flags:
        kb_lines.append(
            f"hl.bind({lua_quote(key_expr)}, {action}, {{ " + ", ".join(flags) + " })"
        )
    else:
        kb_lines.append(f"hl.bind({lua_quote(key_expr)}, {action})")

write_atomic(conf_dir / "generated_keybindings.lua", "\n".join(kb_lines) + "\n")

# ---- generated_autostart.lua ----
auto_lines = [
    "-- AUTOGENERATED FROM settings.json -- DO NOT EDIT",
    'hl.on("hyprland.start", function()',
]
for item in data.get("startup") or []:
    cmd = str(item.get("command") or "").strip()
    if cmd:
        auto_lines.append(f"  hl.exec_cmd({lua_quote(cmd)})")

if data.get("openGuideAtStartup", True):
    auto_lines.append(
        '  hl.exec_cmd("bash -c \'sleep 1 && ~/.config/hypr/scripts/qs_manager.sh toggle guide\'")'
    )

auto_lines += ["end)", ""]
write_atomic(conf_dir / "generated_autostart.lua", "\n".join(auto_lines) + "\n")
PY

    # Keep shell's WALLPAPER_DIR in sync, as the old watcher did.
    local wp_dir
    wp_dir="$(jq -r '.wallpaperDir // empty' "$SETTINGS_FILE" 2>/dev/null || true)"
    if [[ -n "$wp_dir" && -f "$ZSH_RC" ]]; then
        if grep -q '^export WALLPAPER_DIR=' "$ZSH_RC"; then
            sed -i "s|^export WALLPAPER_DIR=.*|export WALLPAPER_DIR=\"$wp_dir\"|" "$ZSH_RC"
        else
            printf '\nexport WALLPAPER_DIR="%s"\n' "$wp_dir" >> "$ZSH_RC"
        fi
    fi

    new_hash="$(
        md5sum \
            "$CONF_DIR/generated_env.lua" \
            "$CONF_DIR/generated_monitors.lua" \
            "$CONF_DIR/generated_keybindings.lua" \
            "$CONF_DIR/generated_autostart.lua" \
            2>/dev/null | md5sum | awk '{print $1}'
    )"

    if [[ "$old_hash" != "$new_hash" ]]; then
        echo "Lua config changed; reloading Hyprland..."
        hyprctl reload full-reset >/dev/null 2>&1 || true
    else
        echo "No Hyprland Lua config changes detected."
    fi
}

if [[ "${1:-}" == "--compile" ]]; then
    compile_settings
    exit 0
fi

echo "Started watching settings.json and calendar .env for changes..."

inotifywait -m -q -e close_write,moved_to --format '%w%f' \
    "$(dirname "$SETTINGS_FILE")" "$(dirname "$ENV_FILE")" |
while read -r filepath; do
    if [[ "$filepath" == "$SETTINGS_FILE" ]]; then
        compile_settings
    elif [[ "$filepath" == "$ENV_FILE" ]]; then
        echo ".env updated; forcing weather refresh..."
        if [[ -x "$WEATHER_SCRIPT" ]]; then
            "$WEATHER_SCRIPT" --getdata &
        elif [[ -f "$WEATHER_SCRIPT" ]]; then
            bash "$WEATHER_SCRIPT" --getdata &
        fi
    fi
done
