# --------------------------------------------------------------------------------------
#
#   ██╗██╗  ██╗   ██╗ █████╗ ███╗   ███╗██╗██████╗  ██████╗ 
#   ██║██║  ╚██╗ ██╔╝██╔══██╗████╗ ████║██║██╔══██╗██╔═══██╗
#   ██║██║   ╚████╔╝ ███████║██╔████╔██║██║██████╔╝██║   ██║
#   ██║██║    ╚██╔╝  ██╔══██║██║╚██╔╝██║██║██╔══██╗██║   ██║
#   ██║███████╗██║   ██║  ██║██║ ╚═╝ ██║██║██║  ██║╚██████╔╝
#   ╚═╝╚══════╝╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝ 
#
#   Created by ilyamiro
#   https://github.com/ilyamiro/nixos-configuration
#
# --------------------------------------------------------------------------------------

source = ~/.config/hypr/colors.conf

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MODULAR CONFIGURATION
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

submap = passthru
# Dummy bind to force Hyprland to register the submap in memory.
# Since you will never press this, all normal keystrokes fall through to Quickshell
bind = SUPER SHIFT CTRL ALT, F35, exec, true
submap = reset

# --------------

source = ~/.config/hypr/config/monitors.conf
source = ~/.config/hypr/config/env.conf
source = ~/.config/hypr/config/autostart.conf
source = ~/.config/hypr/config/variables.conf
source = ~/.config/hypr/config/settings.conf
source = ~/.config/hypr/config/rules.conf
source = ~/.config/hypr/config/keybindings.conf



# macOS-like floating window controls
source = ~/.config/hypr/config/mac-floating.conf


# Keybinds popup
source = ~/.config/hypr/config/keybinds-help.conf

# Central design system
source = ~/.config/hypr/config/design.conf

# Watch central design configuration
exec-once = ~/.config/hypr/scripts/design-watcher.sh

# Control Center
source = ~/.config/hypr/config/control-center.conf

# Live Hotkeys Help
source = ~/.config/hypr/config/hotkeys.conf

# Scratchpad system
source = ~/.config/hypr/config/scratchpad.conf
