# ============================================================
# CONTROL CENTER
# ============================================================

bind = SUPER, ESCAPE, exec, bash ~/.config/hypr/scripts/qs_manager.sh toggle controlcenter
