hl.env("NIXOS_OZONE_WL", "1")
hl.env("XDG_PICTURES_DIR", "/home/ave/Pictures")
hl.env("XDG_VIDEOS_DIR", "/home/ave/Videos")
hl.env("WALLPAPER_DIR", "/home/ave/Pictures/Wallpapers")
hl.env("SCRIPT_DIR", "/home/ave/.config/hypr/scripts")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("__NV_PRIME_RENDER_OFFLOAD", "1")
hl.env("__NV_PRIME_RENDER_OFFLOAD_PROVIDER", "NVIDIA-G0")
hl.env("__GL_GSYNC_ALLOWED", "0")
hl.env("__GL_VRR_ALLOWED", "0")
hl.env("__GL_SHADER_DISK_CACHE", "1")
hl.env("__GL_SHADER_DISK_CACHE_PATH", "/home/ave/.cache/nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
