# ============================================================
# LIVE HOTKEYS HELP
# ============================================================

# Remove old shortcut
unbind = SUPER, backslash
unbind = SUPER, code:51

# Current shortcut
unbind = SUPER, K
bind = SUPER, K, exec, bash ~/.config/hypr/scripts/qs_manager.sh toggle hotkeys
