# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
#  ◈ MAC-LIKE FLOATING WINDOWS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

# SUPER + ALT + LMB
# Pull the window out of the tiling layout and drag it freely.
bind = SUPER ALT, mouse:272, setfloating
bindm = SUPER ALT, mouse:272, movewindow

# SUPER + ALT + wheel UP
# Make floating if necessary and increase size.
bind = SUPER ALT, mouse_up, setfloating
bind = SUPER ALT, mouse_up, resizeactive, 80 80

# SUPER + ALT + wheel DOWN
# Make floating if necessary and decrease size.
bind = SUPER ALT, mouse_down, setfloating
bind = SUPER ALT, mouse_down, resizeactive, -80 -80

# SUPER + ALT + SPACE
# Return all floating windows on the current workspace to tiling.
bind = SUPER ALT, SPACE, exec, ~/.config/hypr/scripts/retile_workspace.sh
