# ============================================================
# AVE SCRATCHPAD SYSTEM
# ============================================================

windowrule {
    name = "ave_scratchpad_terminal"

    match:class = ^(ave-scratchpad)$

    float = on
    size = 1100 720
    center = on
}


# ------------------------------------------------------------
# KEYBINDS
# ------------------------------------------------------------

unbind = SUPER, O
unbind = SUPER, S

# Current window -> centered floating pinned window
bind = SUPER, O, exec, bash ~/.config/hypr/scripts/spotlight-window.sh

# Dedicated Kitty scratchpad
bind = SUPER, S, exec, bash ~/.config/hypr/scripts/kitty-scratchpad.sh
